# Use a minimal base image
FROM alpine:latest
RUN mkdir /vault_binaries
ARG P_VERSION="default"
ENV VERSION_PLUGIN=${P_VERSION}
COPY vault-plugin-aead /vault_binaries/vault-plugin-aead_${VERSION_PLUGIN}