# Use a minimal base image
FROM alpine:latest
RUN mkdir /vault_binaries
ARG P_VERSION="default"
ENV VERSION_PLUGIN=${P_VERSION}
ARG P_NAME=vault-plugin-aead
ENV PLUGIN_NAME=${P_NAME}
COPY vault-plugin-aead /vault_binaries/${PLUGIN_NAME}